


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."descontar_stock_multiple"("items" "jsonb", "p_idempresa" "uuid") RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
declare
  item jsonb;
begin
  for item in
    select * from jsonb_array_elements(items)
  loop
    update articulos
    set stock = stock - (item->>'cantidad')::numeric
    where id = (item->>'idarticulo')::bigint
      and idempresa = p_idempresa;
  end loop;
end;
$$;


ALTER FUNCTION "public"."descontar_stock_multiple"("items" "jsonb", "p_idempresa" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."devolver_stock_multiple"("items" "jsonb", "p_idempresa" "uuid") RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
declare
  item jsonb;
begin
  for item in select * from jsonb_array_elements(items)
  loop
    update articulos
    set stock = stock + (item->>'cantidad')::numeric
    where id = (item->>'idarticulo')::bigint
      and idempresa = p_idempresa;
  end loop;
end;
$$;


ALTER FUNCTION "public"."devolver_stock_multiple"("items" "jsonb", "p_idempresa" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."recalcular_saldo_factura"("p_idfactura" bigint) RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
declare
  v_total numeric(12,2);
  v_pagado numeric(12,2);
  v_saldo numeric(12,2);
  v_estado varchar(20);
begin
  select total
  into v_total
  from public.facturas
  where id = p_idfactura;

  if v_total is null then
    return;
  end if;

  select coalesce(sum(importe_aplicado), 0)
  into v_pagado
  from public.detalle_pagos_clientes
  where idfactura = p_idfactura;

  v_saldo := v_total - v_pagado;

  if v_saldo < 0 then
    v_saldo := 0;
  end if;

  if v_pagado <= 0 then
    v_estado := 'pendiente';
  elsif v_pagado < v_total then
    v_estado := 'parcial';
  else
    v_estado := 'pagada';
  end if;

  update public.facturas
  set
    saldo = v_saldo,
    estado_pago = v_estado
  where id = p_idfactura;
end;
$$;


ALTER FUNCTION "public"."recalcular_saldo_factura"("p_idfactura" bigint) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."trg_recalcular_saldo_factura"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  if tg_op = 'DELETE' then
    perform public.recalcular_saldo_factura(old.idfactura);
    return old;
  else
    perform public.recalcular_saldo_factura(new.idfactura);
    return new;
  end if;
end;
$$;


ALTER FUNCTION "public"."trg_recalcular_saldo_factura"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."articulos" (
    "id" bigint NOT NULL,
    "codigo" character varying(50),
    "descripcion" character varying(200) NOT NULL,
    "precio" numeric(12,2) DEFAULT 0 NOT NULL,
    "stock" numeric(12,2) DEFAULT 0 NOT NULL,
    "idfamilia" bigint,
    "activo" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "imagen_url" "text",
    "precio_costo" numeric(12,2),
    "stock_minimo" integer DEFAULT 0,
    "idempresa" "uuid"
);


ALTER TABLE "public"."articulos" OWNER TO "postgres";


ALTER TABLE "public"."articulos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."articulos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."categorias_monotributo" (
    "categoria" "text" NOT NULL,
    "limite_facturacion" numeric NOT NULL,
    "vigente_desde" "date" DEFAULT CURRENT_DATE
);


ALTER TABLE "public"."categorias_monotributo" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ciudades" (
    "id" bigint NOT NULL,
    "nombre" character varying(120) NOT NULL,
    "idempresa" "uuid",
    "activo" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."ciudades" OWNER TO "postgres";


ALTER TABLE "public"."ciudades" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ciudades_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."clientes" (
    "id" bigint NOT NULL,
    "nombre" character varying(150) NOT NULL,
    "direccion" character varying(200),
    "telefono" character varying(50),
    "email" character varying(120),
    "cuit" character varying(20),
    "idciudad" bigint,
    "idciva" bigint,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "idempresa" "uuid",
    "activo" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."clientes" OWNER TO "postgres";


ALTER TABLE "public"."clientes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."clientes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."compras" (
    "id" bigint NOT NULL,
    "fecha" "date" NOT NULL,
    "idproveedor" bigint,
    "tipo_comprobante" "text",
    "letra_comprobante" "text",
    "numero_comprobante" "text",
    "forma_pago" "text",
    "medio_pago" "text",
    "observaciones" "text",
    "subtotal" numeric DEFAULT 0,
    "total" numeric DEFAULT 0,
    "saldo" numeric DEFAULT 0,
    "estado_pago" "text" DEFAULT 'pendiente'::"text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "punto_venta" "text",
    "idempresa" "uuid",
    "idusuario" "uuid"
);


ALTER TABLE "public"."compras" OWNER TO "postgres";


ALTER TABLE "public"."compras" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."compras_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."condicion_iva" (
    "id" bigint NOT NULL,
    "descripcion" character varying(100) NOT NULL
);


ALTER TABLE "public"."condicion_iva" OWNER TO "postgres";


ALTER TABLE "public"."condicion_iva" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."condicion_iva_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."detalle_compras" (
    "id" bigint NOT NULL,
    "idcompra" bigint,
    "idarticulo" bigint,
    "cantidad" numeric NOT NULL,
    "precio" numeric NOT NULL,
    "subtotal" numeric NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "descripcion" character varying,
    "idempresa" "uuid" DEFAULT "gen_random_uuid"()
);


ALTER TABLE "public"."detalle_compras" OWNER TO "postgres";


ALTER TABLE "public"."detalle_compras" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."detalle_compras_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."detalle_factura" (
    "id" bigint NOT NULL,
    "idfactura" bigint NOT NULL,
    "idarticulo" bigint,
    "descripcion" character varying(200) NOT NULL,
    "cantidad" numeric(12,2) DEFAULT 1 NOT NULL,
    "precio" numeric(12,2) DEFAULT 0 NOT NULL,
    "subtotal" numeric(12,2) DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "idempresa" "uuid",
    "codigo" "text"
);


ALTER TABLE "public"."detalle_factura" OWNER TO "postgres";


ALTER TABLE "public"."detalle_factura" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."detalle_factura_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."detalle_pagos_clientes" (
    "id" bigint NOT NULL,
    "idpago" bigint NOT NULL,
    "idfactura" bigint NOT NULL,
    "importe_aplicado" numeric(12,2) DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."detalle_pagos_clientes" OWNER TO "postgres";


ALTER TABLE "public"."detalle_pagos_clientes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."detalle_pagos_clientes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."detalle_pagos_proveedores" (
    "id" bigint NOT NULL,
    "idpago" bigint NOT NULL,
    "idproveedor" bigint NOT NULL,
    "idfactura" bigint NOT NULL,
    "fecha" "date" DEFAULT CURRENT_DATE NOT NULL,
    "importe_aplicado" numeric(12,2) DEFAULT 0 NOT NULL,
    "observacion" "text",
    "idempresa" "uuid" DEFAULT "gen_random_uuid"()
);


ALTER TABLE "public"."detalle_pagos_proveedores" OWNER TO "postgres";


ALTER TABLE "public"."detalle_pagos_proveedores" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."detalle_pagos_proveedores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."empresas" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "razon_social" "text" NOT NULL,
    "nombre_fantasia" "text",
    "cuit" "text",
    "direccion" "text",
    "telefono" "text",
    "email" "text",
    "activo" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "proximo_remito" integer DEFAULT 1,
    "punto_venta" integer,
    "condicion_iva" "text",
    "ambiente_fiscal" "text" DEFAULT 'homologacion'::"text",
    "categoria_monotributo" "text",
    "idciudad" bigint,
    "provincia" "text",
    "logo_url" "text",
    "certificado_crt" "text",
    "certificado_key" "text",
    "certificado_vencimiento" "date",
    "ingresos_brutos" "text",
    "inicio_actividades" "date",
    "tipo_impresion" character varying(20) DEFAULT 'laser'::character varying NOT NULL
);


ALTER TABLE "public"."empresas" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."facturas" (
    "id" bigint NOT NULL,
    "numero" bigint NOT NULL,
    "fecha" "date" DEFAULT CURRENT_DATE NOT NULL,
    "idcliente" bigint NOT NULL,
    "tipo_comprobante" character varying(20) DEFAULT 'FA'::character varying NOT NULL,
    "forma_pago" character varying(30) DEFAULT 'Contado'::character varying NOT NULL,
    "observaciones" "text",
    "subtotal" numeric(12,2) DEFAULT 0 NOT NULL,
    "total" numeric(12,2) DEFAULT 0 NOT NULL,
    "saldo" numeric(12,2) DEFAULT 0 NOT NULL,
    "estado_pago" character varying(20) DEFAULT 'pendiente'::character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "medio_pago" "text",
    "letra_comprobante" "text",
    "punto_venta" bigint,
    "idempresa" "uuid",
    "idusuario" "uuid",
    "cae" "text",
    "cae_vencimiento" "date",
    "numero_fiscal" integer,
    "estado_fiscal" "text" DEFAULT 'pendiente'::"text",
    "idfactura_origen" bigint,
    "numero_origen" bigint,
    "afip_error_code" "text",
    "afip_error_msg" "text",
    CONSTRAINT "medio_pago_check" CHECK ((("medio_pago" = ANY (ARRAY['efectivo'::"text", 'debito'::"text", 'credito'::"text", 'transferencia'::"text"])) OR ("medio_pago" IS NULL)))
);


ALTER TABLE "public"."facturas" OWNER TO "postgres";


ALTER TABLE "public"."facturas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."facturas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."facturas" ALTER COLUMN "numero" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."facturas_numero_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."familias" (
    "id" bigint NOT NULL,
    "nombre" character varying(120) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "idempresa" "uuid",
    "activo" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."familias" OWNER TO "postgres";


ALTER TABLE "public"."familias" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."familias_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pago_proveedores" (
    "id" bigint NOT NULL,
    "fecha" "date" DEFAULT CURRENT_DATE NOT NULL,
    "idproveedor" bigint NOT NULL,
    "importe" numeric(12,2) DEFAULT 0 NOT NULL,
    "forma_pago" "text",
    "observaciones" "text",
    "comprobante" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "idempresa" "uuid",
    "idusuario" "uuid"
);


ALTER TABLE "public"."pago_proveedores" OWNER TO "postgres";


ALTER TABLE "public"."pago_proveedores" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."pago_proveedores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pagos_clientes" (
    "id" bigint NOT NULL,
    "fecha" "date" DEFAULT CURRENT_DATE NOT NULL,
    "idcliente" bigint NOT NULL,
    "importe" numeric(12,2) DEFAULT 0 NOT NULL,
    "observaciones" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "forma_pago" "text",
    "idempresa" "uuid"
);


ALTER TABLE "public"."pagos_clientes" OWNER TO "postgres";


ALTER TABLE "public"."pagos_clientes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pagos_clientes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."proveedores" (
    "id" bigint NOT NULL,
    "nombre" "text" NOT NULL,
    "direccion" "text",
    "telefono" "text",
    "email" "text",
    "cuit" "text",
    "idciudad" bigint,
    "idciva" bigint,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "idempresa" "uuid",
    "activo" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."proveedores" OWNER TO "postgres";


ALTER TABLE "public"."proveedores" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."proveedores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."usuario_empresa" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "idusuario" "uuid" NOT NULL,
    "idempresa" "uuid" NOT NULL,
    "rol" "text" DEFAULT 'usuario'::"text",
    "activo" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "usuario_empresa_rol_check" CHECK (("rol" = ANY (ARRAY['admin'::"text", 'usuario'::"text", 'vendedor'::"text", 'contador'::"text"])))
);


ALTER TABLE "public"."usuario_empresa" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."usuarios" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "nombre" "text" NOT NULL,
    "email" "text" NOT NULL,
    "password" "text",
    "rol_global" "text" DEFAULT 'usuario'::"text",
    "activo" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "usuario" "text",
    "superusuario" boolean DEFAULT false,
    "auth_user_id" "uuid",
    "debe_cambiar_password" boolean DEFAULT true NOT NULL,
    CONSTRAINT "usuarios_rol_global_check" CHECK (("rol_global" = ANY (ARRAY['superadmin'::"text", 'admin'::"text", 'usuario'::"text"])))
);


ALTER TABLE "public"."usuarios" OWNER TO "postgres";


ALTER TABLE ONLY "public"."articulos"
    ADD CONSTRAINT "articulos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."categorias_monotributo"
    ADD CONSTRAINT "categorias_monotributo_pkey" PRIMARY KEY ("categoria");



ALTER TABLE ONLY "public"."ciudades"
    ADD CONSTRAINT "ciudades_nombre_idempresa_key" UNIQUE ("nombre", "idempresa");



ALTER TABLE ONLY "public"."ciudades"
    ADD CONSTRAINT "ciudades_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."clientes"
    ADD CONSTRAINT "clientes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."compras"
    ADD CONSTRAINT "compras_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."condicion_iva"
    ADD CONSTRAINT "condicion_iva_descripcion_key" UNIQUE ("descripcion");



ALTER TABLE ONLY "public"."condicion_iva"
    ADD CONSTRAINT "condicion_iva_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."detalle_compras"
    ADD CONSTRAINT "detalle_compras_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."detalle_factura"
    ADD CONSTRAINT "detalle_factura_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."detalle_pagos_clientes"
    ADD CONSTRAINT "detalle_pagos_clientes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."detalle_pagos_proveedores"
    ADD CONSTRAINT "detalle_pagos_proveedores_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."empresas"
    ADD CONSTRAINT "empresas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."facturas"
    ADD CONSTRAINT "facturas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."familias"
    ADD CONSTRAINT "familias_nombre_key" UNIQUE ("nombre");



ALTER TABLE ONLY "public"."familias"
    ADD CONSTRAINT "familias_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pago_proveedores"
    ADD CONSTRAINT "pago_proveedores_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pagos_clientes"
    ADD CONSTRAINT "pagos_clientes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."proveedores"
    ADD CONSTRAINT "proveedores_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."usuario_empresa"
    ADD CONSTRAINT "usuario_empresa_idusuario_idempresa_key" UNIQUE ("idusuario", "idempresa");



ALTER TABLE ONLY "public"."usuario_empresa"
    ADD CONSTRAINT "usuario_empresa_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "usuarios_auth_user_id_key" UNIQUE ("auth_user_id");



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "usuarios_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "usuarios_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "usuarios_usuario_key" UNIQUE ("usuario");



CREATE UNIQUE INDEX "idx_articulos_codigo_unique" ON "public"."articulos" USING "btree" ("codigo") WHERE ("codigo" IS NOT NULL);



CREATE OR REPLACE TRIGGER "trigger_recalcular_saldo_factura" AFTER INSERT OR DELETE OR UPDATE ON "public"."detalle_pagos_clientes" FOR EACH ROW EXECUTE FUNCTION "public"."trg_recalcular_saldo_factura"();



ALTER TABLE ONLY "public"."articulos"
    ADD CONSTRAINT "articulos_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id");



ALTER TABLE ONLY "public"."ciudades"
    ADD CONSTRAINT "ciudades_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id");



ALTER TABLE ONLY "public"."clientes"
    ADD CONSTRAINT "clientes_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id");



ALTER TABLE ONLY "public"."compras"
    ADD CONSTRAINT "compras_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id");



ALTER TABLE ONLY "public"."compras"
    ADD CONSTRAINT "compras_idproveedor_fkey" FOREIGN KEY ("idproveedor") REFERENCES "public"."proveedores"("id");



ALTER TABLE ONLY "public"."compras"
    ADD CONSTRAINT "compras_idusuario_fkey" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("id");



ALTER TABLE ONLY "public"."detalle_compras"
    ADD CONSTRAINT "detalle_compras_idarticulo_fkey" FOREIGN KEY ("idarticulo") REFERENCES "public"."articulos"("id");



ALTER TABLE ONLY "public"."detalle_compras"
    ADD CONSTRAINT "detalle_compras_idcompra_fkey" FOREIGN KEY ("idcompra") REFERENCES "public"."compras"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."detalle_factura"
    ADD CONSTRAINT "detalle_factura_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id");



ALTER TABLE ONLY "public"."empresas"
    ADD CONSTRAINT "empresas_idciudad_fkey" FOREIGN KEY ("idciudad") REFERENCES "public"."ciudades"("id");



ALTER TABLE ONLY "public"."facturas"
    ADD CONSTRAINT "facturas_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id");



ALTER TABLE ONLY "public"."facturas"
    ADD CONSTRAINT "facturas_idusuario_fkey" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("id");



ALTER TABLE ONLY "public"."familias"
    ADD CONSTRAINT "familias_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id");



ALTER TABLE ONLY "public"."articulos"
    ADD CONSTRAINT "fk_articulos_familia" FOREIGN KEY ("idfamilia") REFERENCES "public"."familias"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."clientes"
    ADD CONSTRAINT "fk_clientes_ciudad" FOREIGN KEY ("idciudad") REFERENCES "public"."ciudades"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."clientes"
    ADD CONSTRAINT "fk_clientes_civa" FOREIGN KEY ("idciva") REFERENCES "public"."condicion_iva"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."detalle_factura"
    ADD CONSTRAINT "fk_detalle_articulo" FOREIGN KEY ("idarticulo") REFERENCES "public"."articulos"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."detalle_factura"
    ADD CONSTRAINT "fk_detalle_factura" FOREIGN KEY ("idfactura") REFERENCES "public"."facturas"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."detalle_pagos_clientes"
    ADD CONSTRAINT "fk_detalle_pago" FOREIGN KEY ("idpago") REFERENCES "public"."pagos_clientes"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."detalle_pagos_clientes"
    ADD CONSTRAINT "fk_detalle_pago_factura" FOREIGN KEY ("idfactura") REFERENCES "public"."facturas"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."facturas"
    ADD CONSTRAINT "fk_facturas_cliente" FOREIGN KEY ("idcliente") REFERENCES "public"."clientes"("id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."pagos_clientes"
    ADD CONSTRAINT "fk_pagos_clientes_cliente" FOREIGN KEY ("idcliente") REFERENCES "public"."clientes"("id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."pago_proveedores"
    ADD CONSTRAINT "pago_proveedores_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id");



ALTER TABLE ONLY "public"."pago_proveedores"
    ADD CONSTRAINT "pago_proveedores_idproveedor_fkey" FOREIGN KEY ("idproveedor") REFERENCES "public"."proveedores"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pago_proveedores"
    ADD CONSTRAINT "pago_proveedores_idusuario_fkey" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("id");



ALTER TABLE ONLY "public"."pagos_clientes"
    ADD CONSTRAINT "pagos_clientes_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id");



ALTER TABLE ONLY "public"."proveedores"
    ADD CONSTRAINT "proveedores_idciudad_fkey" FOREIGN KEY ("idciudad") REFERENCES "public"."ciudades"("id");



ALTER TABLE ONLY "public"."proveedores"
    ADD CONSTRAINT "proveedores_idciva_fkey" FOREIGN KEY ("idciva") REFERENCES "public"."condicion_iva"("id");



ALTER TABLE ONLY "public"."proveedores"
    ADD CONSTRAINT "proveedores_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id");



ALTER TABLE ONLY "public"."usuario_empresa"
    ADD CONSTRAINT "usuario_empresa_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."usuario_empresa"
    ADD CONSTRAINT "usuario_empresa_idusuario_fkey" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "usuarios_auth_user_id_fkey" FOREIGN KEY ("auth_user_id") REFERENCES "auth"."users"("id");



CREATE POLICY "Permitir actualizar pago proveedores" ON "public"."pago_proveedores" FOR UPDATE TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "Permitir actualizar proveedores" ON "public"."proveedores" FOR UPDATE TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "Permitir eliminar pago proveedores" ON "public"."pago_proveedores" FOR DELETE TO "authenticated", "anon" USING (true);



CREATE POLICY "Permitir eliminar proveedores" ON "public"."proveedores" FOR DELETE TO "authenticated", "anon" USING (true);



CREATE POLICY "Permitir insertar pago proveedores" ON "public"."pago_proveedores" FOR INSERT TO "authenticated", "anon" WITH CHECK (true);



CREATE POLICY "Permitir insertar proveedores" ON "public"."proveedores" FOR INSERT TO "authenticated", "anon" WITH CHECK (true);



CREATE POLICY "Permitir lectura categorias monotributo" ON "public"."categorias_monotributo" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Permitir leer pago proveedores" ON "public"."pago_proveedores" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Permitir leer proveedores" ON "public"."proveedores" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."pago_proveedores" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."proveedores" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."descontar_stock_multiple"("items" "jsonb", "p_idempresa" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."descontar_stock_multiple"("items" "jsonb", "p_idempresa" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."descontar_stock_multiple"("items" "jsonb", "p_idempresa" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."devolver_stock_multiple"("items" "jsonb", "p_idempresa" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."devolver_stock_multiple"("items" "jsonb", "p_idempresa" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."devolver_stock_multiple"("items" "jsonb", "p_idempresa" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."recalcular_saldo_factura"("p_idfactura" bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."recalcular_saldo_factura"("p_idfactura" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."recalcular_saldo_factura"("p_idfactura" bigint) TO "service_role";



GRANT ALL ON FUNCTION "public"."trg_recalcular_saldo_factura"() TO "anon";
GRANT ALL ON FUNCTION "public"."trg_recalcular_saldo_factura"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."trg_recalcular_saldo_factura"() TO "service_role";


















GRANT ALL ON TABLE "public"."articulos" TO "anon";
GRANT ALL ON TABLE "public"."articulos" TO "authenticated";
GRANT ALL ON TABLE "public"."articulos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."articulos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."articulos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."articulos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."categorias_monotributo" TO "anon";
GRANT ALL ON TABLE "public"."categorias_monotributo" TO "authenticated";
GRANT ALL ON TABLE "public"."categorias_monotributo" TO "service_role";



GRANT ALL ON TABLE "public"."ciudades" TO "anon";
GRANT ALL ON TABLE "public"."ciudades" TO "authenticated";
GRANT ALL ON TABLE "public"."ciudades" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ciudades_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ciudades_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ciudades_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."clientes" TO "anon";
GRANT ALL ON TABLE "public"."clientes" TO "authenticated";
GRANT ALL ON TABLE "public"."clientes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."clientes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."clientes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."clientes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."compras" TO "anon";
GRANT ALL ON TABLE "public"."compras" TO "authenticated";
GRANT ALL ON TABLE "public"."compras" TO "service_role";



GRANT ALL ON SEQUENCE "public"."compras_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."compras_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."compras_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."condicion_iva" TO "anon";
GRANT ALL ON TABLE "public"."condicion_iva" TO "authenticated";
GRANT ALL ON TABLE "public"."condicion_iva" TO "service_role";



GRANT ALL ON SEQUENCE "public"."condicion_iva_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."condicion_iva_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."condicion_iva_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."detalle_compras" TO "anon";
GRANT ALL ON TABLE "public"."detalle_compras" TO "authenticated";
GRANT ALL ON TABLE "public"."detalle_compras" TO "service_role";



GRANT ALL ON SEQUENCE "public"."detalle_compras_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."detalle_compras_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."detalle_compras_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."detalle_factura" TO "anon";
GRANT ALL ON TABLE "public"."detalle_factura" TO "authenticated";
GRANT ALL ON TABLE "public"."detalle_factura" TO "service_role";



GRANT ALL ON SEQUENCE "public"."detalle_factura_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."detalle_factura_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."detalle_factura_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."detalle_pagos_clientes" TO "anon";
GRANT ALL ON TABLE "public"."detalle_pagos_clientes" TO "authenticated";
GRANT ALL ON TABLE "public"."detalle_pagos_clientes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."detalle_pagos_clientes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."detalle_pagos_clientes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."detalle_pagos_clientes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."detalle_pagos_proveedores" TO "anon";
GRANT ALL ON TABLE "public"."detalle_pagos_proveedores" TO "authenticated";
GRANT ALL ON TABLE "public"."detalle_pagos_proveedores" TO "service_role";



GRANT ALL ON SEQUENCE "public"."detalle_pagos_proveedores_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."detalle_pagos_proveedores_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."detalle_pagos_proveedores_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."empresas" TO "anon";
GRANT ALL ON TABLE "public"."empresas" TO "authenticated";
GRANT ALL ON TABLE "public"."empresas" TO "service_role";



GRANT ALL ON TABLE "public"."facturas" TO "anon";
GRANT ALL ON TABLE "public"."facturas" TO "authenticated";
GRANT ALL ON TABLE "public"."facturas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."facturas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."facturas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."facturas_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."facturas_numero_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."facturas_numero_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."facturas_numero_seq" TO "service_role";



GRANT ALL ON TABLE "public"."familias" TO "anon";
GRANT ALL ON TABLE "public"."familias" TO "authenticated";
GRANT ALL ON TABLE "public"."familias" TO "service_role";



GRANT ALL ON SEQUENCE "public"."familias_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."familias_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."familias_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pago_proveedores" TO "anon";
GRANT ALL ON TABLE "public"."pago_proveedores" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."pago_proveedores" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pago_proveedores_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pago_proveedores_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pago_proveedores_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pagos_clientes" TO "anon";
GRANT ALL ON TABLE "public"."pagos_clientes" TO "authenticated";
GRANT ALL ON TABLE "public"."pagos_clientes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pagos_clientes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pagos_clientes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pagos_clientes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."proveedores" TO "anon";
GRANT ALL ON TABLE "public"."proveedores" TO "authenticated";
GRANT ALL ON TABLE "public"."proveedores" TO "service_role";



GRANT ALL ON SEQUENCE "public"."proveedores_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."proveedores_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."proveedores_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."usuario_empresa" TO "anon";
GRANT ALL ON TABLE "public"."usuario_empresa" TO "authenticated";
GRANT ALL ON TABLE "public"."usuario_empresa" TO "service_role";



GRANT ALL ON TABLE "public"."usuarios" TO "anon";
GRANT ALL ON TABLE "public"."usuarios" TO "authenticated";
GRANT ALL ON TABLE "public"."usuarios" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































